### ISSUE TITLE
Where is the file under \test_run\resources\insightFace_model ? How can I download it? Or how can I generate it?

### ISSUE THREAD

**Issue by gclsoft** [Danbinabo/insighrface#5]
Where is the file under \test_run\resources\insightFace_model ? How can I download it? Or how can I generate it?
I had copied `model-0000.params` from insightface's github, but others files I don't know where to copy.
Thanks!
```
[16:22:38] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
[16:22:38] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2.4\helpers\pydev\pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/ai/new/insighrface_camera_gcl/test_run/2_demo.py", line 253, in <module>
    personName_list = get_personName_list(rgb_3d_array, box_2d_array, point_2d_array)
  File "C:/ai/new/insighrface_camera_gcl/test_run/2_demo.py", line 125, in get_personName_list
    personName = face_recognizer.get_personName_1(affine_image_3d_array)
  File "C:\ai\new\insighrface_camera_gcl\test_run\FaceRecognizer.py", line 244, in get_personName_1
    feature_2d_array = self.face_vectorizer.get_feature_2d_array(image_4d_array)
  File "C:\ai\new\insighrface_camera_gcl\test_run\FaceRecognizer.py", line 59, in get_feature_2d_array
    self.model = load_model(batch_size=self.batch_size)
  File "C:\ai\new\insighrface_camera_gcl\test_run\FaceRecognizer.py", line 23, in load_model
    model.set_params(arg_params, auxiliary_params)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\module\module.py", line 350, in set_params
    allow_extra=allow_extra)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\module\module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\module\module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: bn0_beta is not presented
```

**Comment by gclsoft** [comment]
find it now , it's in the readme.md file.
